/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface NFTTemplateSettings {
  $schema?: string;
  /**
   * Name of the NFT
   */
  name: string;
  contractOwner?: ContractOwner;
  ustxPrice?: USTXPrice;
  nycPrice?: NYCPrice;
  miaPrice?: MIAPrice;
  mintLimit?: MintLimit;
  /**
   * Early bird access. Leave empty to disable this feature
   */
  allowList?: {
    /**
     * List of Stacks addresses
     */
    addresses: string[];
    allowAllAtBlockHeight?: AllowAllAtBlockHeight;
  };
}
/**
 * Stacks address allowed to perform changes to the NFT contracts settings
 */
export interface ContractOwner {
  value: string;
  updatable?: boolean;
}
/**
 * Mint price in USTX. `undefined` to disable mint in STX
 */
export interface USTXPrice {
  value: number;
  updatable?: boolean;
}
/**
 * Mint price in NYC Citycoins. `undefined` to disable mint in NYC
 */
export interface NYCPrice {
  value: number;
  updatable?: boolean;
}
/**
 * Mint price in MIA Citycoins. `undefined` to disable mint in MIA
 */
export interface MIAPrice {
  value: number;
  updatable?: boolean;
}
/**
 * Mint limit per STX address. Leave empty to disable.
 */
export interface MintLimit {
  value: number;
  updatable?: boolean;
}
/**
 * Allow everyone to mint from this block height. Leave empty to disable mint for all
 */
export interface AllowAllAtBlockHeight {
  value: number;
  updatable?: boolean;
}
