/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type OwnerAddress = string;
export type OwnerCanBeUpdatedAfterDeploy = boolean;
export type MintNFTWithTokens = ("STX" | "MIA" | "NYC")[];
export type ValueInUSTX = number;
export type USTXPriceCanBeUpdatedAfterDeploy = boolean;
export type NYCPriceCanBeUpdatedAfterDeploy = boolean;
export type MIAPriceCanBeUpdatedAfterDeploy = boolean;
export type MintLimitCanBeUpdatedAfterDeploy = boolean;

export interface NFTTemplateSettings {
  $schema?: string;
  /**
   * Name of the NFT
   */
  name: string;
  contractOwner?: ContractOwner;
  tokens?: MintNFTWithTokens;
  ustxPrice?: USTXPrice;
  nycPrice?: NYCPrice;
  miaPrice?: MIAPrice;
  mintLimit?: MintLimit;
  /**
   * Early bird access. Leave empty to disable this feature
   */
  allowList?: {
    /**
     * List of Stacks addresses
     */
    addresses?: string[];
    allowAllAtBlockHeight?: AllowAllAtBlockHeight;
  };
}
/**
 * Stacks address for the owner of this NFT contract. This address will be allowed to perform changes to the NFT contract's settings.
 */
export interface ContractOwner {
  value: OwnerAddress;
  updatable?: OwnerCanBeUpdatedAfterDeploy;
}
/**
 * Mint price in USTX. Leave this empty to disable mint in STX.
 */
export interface USTXPrice {
  value: ValueInUSTX;
  updatable?: USTXPriceCanBeUpdatedAfterDeploy;
}
/**
 * Mint price in NYC Citycoins. Leave this empty to disable mint in NYC.
 */
export interface NYCPrice {
  value?: number;
  updatable?: NYCPriceCanBeUpdatedAfterDeploy;
}
/**
 * Mint price in MIA Citycoins. Leave this empty to disable mint in MIA.
 */
export interface MIAPrice {
  value?: number;
  updatable?: MIAPriceCanBeUpdatedAfterDeploy;
}
/**
 * Mint limit per STX address. Leave empty for unlimited.
 */
export interface MintLimit {
  value?: number;
  updatable?: MintLimitCanBeUpdatedAfterDeploy;
}
/**
 * Allow everyone to mint from this block height. Leave empty to disable mint for all
 */
export interface AllowAllAtBlockHeight {
  value: number;
  updatable?: boolean;
}
