/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type OwnerAddress = string;
export type OwnerCanBeUpdatedAfterDeploy = boolean;
export type TokenURIBase1 = string;
export type TokenURIBaseCanBeUpdatedAfterDeploy = boolean;
/**
 * Define if NFTs can be minted with STX and or Citycoins (NYC, MIA)
 */
export type MintCurrenciesSettings = {
  [k: string]: unknown;
};
export type MintLimitCanBeUpdatedAfterDeploy = boolean;
/**
 * Add Stacks addresses to allow early access.
 */
export type AllowedAddresses = string[];
export type BlockHeight = number;

export interface NFTTemplateSettings {
  $schema?: string;
  general: GeneralSettings;
  currency?: MintCurrenciesSettings;
  mint?: MintSettings;
}
export interface GeneralSettings {
  /**
   * Name of the NFT
   */
  name: string;
  "contract-owner"?: ContractOwner;
  "token-uri-base": TokenURIBase;
}
/**
 * Stacks address for the owner of this NFT contract. This address will be allowed to perform changes to the NFT contract's settings.
 */
export interface ContractOwner {
  value: OwnerAddress;
  updatable?: OwnerCanBeUpdatedAfterDeploy;
}
/**
 * Base URI for the NFT image.
 */
export interface TokenURIBase {
  value: TokenURIBase1;
  updatable?: TokenURIBaseCanBeUpdatedAfterDeploy;
}
/**
 * Mint settings such as limit and early birds
 */
export interface MintSettings {
  "mint-limit"?: MintLimit;
  "allow-list"?: EarlyBirdAccess;
  [k: string]: unknown;
}
/**
 * Mint limit per STX address. Leave empty for unlimited.
 */
export interface MintLimit {
  value?: number;
  updatable?: MintLimitCanBeUpdatedAfterDeploy;
}
/**
 * Allow addresses to claim early access to your NFT.
 */
export interface EarlyBirdAccess {
  addresses?: AllowedAddresses;
  "allow-all-at-block-height"?: AllowAllAtBlockHeight;
}
/**
 * Allow everyone to mint from this block height. Leave empty to disable mint for all.
 */
export interface AllowAllAtBlockHeight {
  value: BlockHeight;
  updatable?: boolean;
}
